language: node_js
node_js:
  - 12
services:
  - postgresql
addons:
  postgresql: '10'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "personalwebsite-test";' -U postgres
script:
  - npm test
  - npm run build-client

